[package]
name = "advent-of-code-2024"
version = "0.2.0"
authors = ["John Erickson <john.t.erickson@gmail.com>"]
edition = "2021"

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
itertools = "*"
lazy_static = "*"
nom = "7.1.3"
pathfinding = "*"
strum = "*"
strum_macros = "*"
