[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"