[package]
name = "advent-of-code-2021"
version = "0.2.0"
authors = ["John Erickson <john.t.erickson@gmail.com>"]
edition = "2021"

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
itertools = "0.10.2"
lazy_static = "1.4.0"
pathfinding = "3.0.5"